import {Vector3,Vector2,IEntity,IPed,IPlayer,IVehicle,IObject,IBlip,ICamera} from '@risinglife/fivem-shared'
import * as app from './namespaces/app';
import * as audio from './namespaces/audio';
import * as brain from './namespaces/brain';
import * as builtin from './namespaces/builtin';
import * as camera from './namespaces/camera';
import * as clock from './namespaces/clock';
import * as cutscene from './namespaces/cutscene';
import * as datafile from './namespaces/datafile';
import * as decorator from './namespaces/decorator';
import * as dlc from './namespaces/dlc';
import * as entity from './namespaces/entity';
import * as event from './namespaces/event';
import * as extrametadata from './namespaces/extrametadata';
import * as fire from './namespaces/fire';
import * as graphics from './namespaces/graphics';
import * as hud from './namespaces/hud';
import * as interior from './namespaces/interior';
import * as itemset from './namespaces/itemset';
import * as lobby from './namespaces/lobby';
import * as localization from './namespaces/localization';
import * as misc from './namespaces/misc';
import * as mobile from './namespaces/mobile';
import * as money from './namespaces/money';
import * as netshopping from './namespaces/netshopping';
import * as network from './namespaces/network';
import * as object from './namespaces/object';
import * as pad from './namespaces/pad';
import * as pathfind from './namespaces/pathfind';
import * as ped from './namespaces/ped';
import * as physics from './namespaces/physics';
import * as player from './namespaces/player';
import * as recording from './namespaces/recording';
import * as replay from './namespaces/replay';
import * as savemigration from './namespaces/savemigration';
import * as script from './namespaces/script';
import * as security from './namespaces/security';
import * as shapetest from './namespaces/shapetest';
import * as socialclub from './namespaces/socialclub';
import * as stats from './namespaces/stats';
import * as streaming from './namespaces/streaming';
import * as task from './namespaces/task';
import * as vehicle from './namespaces/vehicle';
import * as water from './namespaces/water';
import * as weapon from './namespaces/weapon';
import * as zone from './namespaces/zone';

export { app, audio, brain, builtin, camera, clock, cutscene, datafile, decorator, dlc, entity, event, extrametadata, fire, graphics, hud, interior, itemset, lobby, localization, misc, mobile, money, netshopping, network, object, pad, pathfind, ped, physics, player, recording, replay, savemigration, script, security, shapetest, socialclub, stats, streaming, task, vehicle, water, weapon, zone };

export * from '@risinglife/fivem-shared';